### ISSUE TITLE
Certain models do not load due to console error

### ISSUE THREAD

**Issue by fabasoft-maxm** [xeokit/xeokit-sdk#985]
**Describe the bug**
When i'm trying to load certain models using `GLTFLoaderPlugin.load`, i get this console error:
`Uncaught (in promise) TypeError: ctx.log is not a function`

The error is thrown in the file "GLTFVBOSceneModelLoader.js" at line 619: https://github.com/xeokit/xeokit-sdk/blob/5819eb58ceeaaf6ab61737d8e0261315f2a70783/src/plugins/GLTFLoaderPlugin/GLTFVBOSceneModelLoader.js#L619

While looking through this file i found that `const ctx` does not even have a log function:

![image](https://user-images.githubusercontent.com/122608555/212307782-948ea38c-2a9c-424a-88ff-4b30b53cf539.png)

It seems as if the `ctx.log` function is not yet implemented but gets called in this file nonetheless.
I tried patching it by commenting out this line and all of my files were loaded correctly again.

**Expected behavior**
ctx.log doesn't get called until the function is actually implemented.

**Additional context**
This error started appearing after upgrading xeokit-sdk from 2.2.2 to 2.3.2.

**Comment by xeolabs** [comment]
Fixed in @xeokit/xeokit-sdk@2.3.6

**Comment by fabasoft-maxm** [comment]
Thanks for the quick bug-fix! :)
